[platformio]
default_envs = m5stick-c-plus

[env:m5stick-c-plus]
platform = espressif32@^6.5.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_M5StickC_Plus
    -std=gnu++17
    -Wall -Wswitch-enum
lib_deps =
    m5stack/M5Unified@^0.2.14

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -D UNIT_TEST
    -Wall -Wextra
    -I include
test_build_src = yes
